matrix:
   include:
      - language: python
        python: 2.7
        before_script:
            - cd python

      - language: perl
        perl: 5.26
        before_script:
            - cd perl
