#!/bin/bash

TXT='detected sudo using:\e[31m'

if [[ $EUID -eq 0 && $SUDO_COMMAND == "$0" ]]; then echo -e $TXT "\$SUDO_COMMAND\e[0m"; fi
if [[ $EUID -eq 0 && -n `ps -ef | grep "sudo $0$"` ]]; then echo -e $TXT "processes\e[0m"; fi

echo "Script $0 executed..."
