#!/bin/bash
#
# Prints configured users (uid above 1000), input is taken from passwd database
# @MZvk : 2017 [A54477]
#

echo -e "+---------+------+------+----------------------+------ ---- -- - "
echo -e "|  \e[33muser\e[0m   | \e[33muid\e[0m  | \e[33mgid\e[0m  | \e[33mfull name\e[0m            | \e[33memail\e[0m "
echo "+---------+------+------+----------------------+------------- --- -- -"
if [ "$EUID" -eq 0 ]; then
getent passwd | awk -F'[:,]' '$3 >= 1000 && $3 < 5000 \
                {ch = 0; for(col = 6; col <= NF; col++){if(match($col, /.*@.*/) && ch != col) {ch = col; mail = $col}} \
                if(ch == 0) mail = " --- "; \
                {cmd = "grep "$1" /etc/shadow | cut -d: -f8"; cmd |getline uexp; close(cmd); usts = " ";} \
                if(uexp !~ /^$/) usts = "\033[31m*\033[0m"; \
                printf "|%s%-7s | %.4d | %.4d | %-20s | %s \n", usts, $1, $3, $4, $5, mail}' | sort -t'|' -nk3
else
getent passwd | awk -F'[:,]' '$3 >= 1000 && $3 < 5000 \
                {ch = 0; for(col = 6; col <= NF; col++){if(match($col, /.*@.*/) && ch != col) {ch = col; mail = $col}} \
                if(ch == 0) mail = " --- "; \
                printf "| %-7s | %.4d | %.4d | %-20s | %s \n", $1, $3, $4, $5, mail}' | sort -t'|' -nk3
fi
echo "+---------+------+------+----------------------+----- --- --- -- - "
echo -e " \e[31m*\e[0m - expired users (only for root)"

#ideas
# -e/r - expire/restore account
# -a/d - add/del account
