#!/bin/bash
# MZvk|A544778

OSVR=`hostnamectl | grep System | awk '{print $3}'`' '`[ -r /etc/debian_version ] && cat /etc/debian_version`
CHAS=`hostnamectl | grep Chassis | awk '{print $2}'`
VIRT=`hostnamectl | grep Virtualization | awk '{print $2}'`
LOAD=`cat /proc/loadavg | awk '{print $1}'`
MEMU=`free | awk '/Mem:/ { printf "%05.2f%%", ($2 - $4 - $6 - $7)/$2*100 }'`

echo "-- $(date -u) --"
echo && echo "  Welcome to $(hostname)"
printf "  -----\n  OS:  %s (%s) [%s : %s]\n" "$OSVR" "$(uname -r)" "$CHAS" "$VIRT"
echo "$LOAD" "$(grep 'model name' /proc/cpuinfo | wc -l)" | awk '{ printf "  CPU: %05.2f%%\n",$1 * 100 / $2 }'
echo "  MEM: $MEMU"
[ -r /etc/sysuse ] && echo "  USE: `cat /etc/sysuse`"
echo && echo "-- ENJOY --"
